name: caldav_client
description: A CalDAV client for dart. It allows to make CalDAV
  requests to a server easily and quickly.
version: 1.0.0
repository: https://github.com/julisanchez/caldav_client
issue_tracker: https://github.com/julisanchez/caldav_client/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^5.0.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  mock_web_server: ^5.0.0-nullsafety.1
