name: caldav_client
description: A starting point for Dart libraries or applications.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  xml: ^5.0.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
